### ISSUE TITLE
Memory leak in ReloadFonts()

### ISSUE THREAD

**Issue by nagolove** [raylib-extras/rlImGui#45]
Hello. 
I use `rlImGui` in my C project(also with `raylib` and `cimgui`). I use commit 16db43e57d67e09afdc19216f1ef9d1542d5fdac
AddressSanitizer showing a direct memory leak:
```
Direct leak of 20 byte(s) in 1 object(s) allocated from:
    #0 0x7f969b8e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x556aded52c34 in MemAlloc /home/nagolove/caustic/3rd_party/raylib/src/utils.c:165
    #2 0x556adee88261 in ReloadFonts() (/home/nagolove/proekt80/t80+0x724261) (BuildId: 08d4b93d2575458a72636d1b4d463d8c1b0a88f8)
    #3 0x556adee88b1f in rlImGuiEndInitImGui (/home/nagolove/proekt80/t80+0x724b1f) (BuildId: 08d4b93d2575458a72636d1b4d463d8c1b0a88f8)
    #4 0x556adee89b9f in rlImGuiSetup (/home/nagolove/proekt80/t80+0x725b9f) (BuildId: 08d4b93d2575458a72636d1b4d463d8c1b0a88f8)
    #5 0x556adea6df17 in main /home/nagolove/proekt80/src/t80_main.c:480
    #6 0x7f969b245ccf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```
There is no `MemFree()` call for `io.Fonts->TexID`
I suggest next patch for shutdown function:
```c++
void rlImGuiShutdown()
{
    ImGui::SetCurrentContext(GlobalContext);

    ImGuiIO& io = ImGui::GetIO();
    if (io.Fonts->TexID) {
        MemFree(io.Fonts->TexID);
        io.Fonts->TexID = NULL;
    }

    ImGui_ImplRaylib_Shutdown();

    ImGui::DestroyContext();
}
```

**Comment by JeffM2501** [comment]
Thank you for the report, I have pushed a fix. The fix needs to go into ImGui_ImplRaylib_Shutdown because that's where we unload the font. The fix you posted doubles up that work. also ImGui_ImplRaylib_Shutdown needs the fix too.
